#!/usr/bin/env python3
"""Write THIRD-PARTY.md: every crate compiled into the firmware image, with its licence.

The list comes from `cargo metadata` for the device target. It follows normal dependencies from
`teetotum-firmware` and stops at proc-macros, which run on the build host and leave no code in
the image. Feature unification can still list a crate the linker later drops, so the list errs
on the long side.

    tools/third-party.py            rewrite THIRD-PARTY.md
    tools/third-party.py --check    exit 1 if THIRD-PARTY.md is out of date
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = "xtensa-esp32s3-none-elf"
OUT = ROOT / "THIRD-PARTY.md"

# Crates whose metadata carries no SPDX expression.
LICENSE_OVERRIDE = {
    "u8g2-fonts": "MIT OR Apache-2.0 (code); fonts: see [`teetotum/LICENSE-FONTS`](teetotum/LICENSE-FONTS)",
}

HEADER = """\
# Third-party components

This repository contains no third-party source code. What it builds does: the firmware image
links the crates below, and it embeds the Helvetica bitmap fonts from U8g2. Anyone who
distributes a built image carries the obligations of these licences, which for almost all of
them means shipping their copyright notices along with it.

This file is generated by `tools/third-party.py` from `Cargo.lock`; do not edit it by hand.

## Not under a crate licence

| Component | Where | Licence |
|---|---|---|
| Helvetica bitmap fonts (helvB14, helvB18, helvB24, helvR14, helvR18), converted by U8g2 | embedded in the firmware image via `u8g2-fonts` | Adobe / Digital Equipment Corporation permission notice, verbatim in [`teetotum/LICENSE-FONTS`](teetotum/LICENSE-FONTS) |
| Espressif Wi-Fi, Bluetooth, PHY and ROM libraries (precompiled `.a`) | linked into the firmware image via `esp-wifi-sys-esp32s3` and `esp-rom-sys` | as declared by those crates, listed below |
| Rust `core`, `alloc`, `compiler_builtins` | firmware image and every plugin `.wasm` | MIT OR Apache-2.0 |

## Build-time only

These run on the build host and leave nothing in the image except what they compute.

| Crate | Used for | Licence |
|---|---|---|
| `qrcodegen` | encodes the QR codes of the Home ring into constant module data (`firmware/build.rs`) | MIT |
| proc-macro crates such as `trouble-host-macros`, `embassy-executor-macros` | code generation | see each crate |

The plugins in `plugins/` depend only on `teetotum-face` from this repository.

## Crates in the firmware image

| Crate | Version | Licence | Source |
|---|---|---|---|
"""


def spdx(name, raw):
    if name in LICENSE_OVERRIDE:
        return LICENSE_OVERRIDE[name]
    if raw is None:
        return "unknown, see source"
    # Older crates write `MIT/Apache-2.0`; `/` meant OR.
    return " OR ".join(part.strip() for part in raw.split("/"))


def cargo(*args):
    return subprocess.run(["cargo", *args, "--locked"], cwd=ROOT, check=True,
                          capture_output=True, text=True).stdout


def linked_crates():
    # `cargo tree` resolves features per target; `cargo metadata` would also list the radio
    # blobs of every other Espressif chip.
    tree = cargo("tree", "-e", "normal,no-proc-macro", "--target", TARGET,
                 "-p", "teetotum-firmware", "--prefix", "none", "-f", "{p}")
    wanted = set()
    for line in tree.splitlines():
        name, version = line.split()[:2]
        wanted.add((name, version.lstrip("v")))
    meta = json.loads(cargo("metadata", "--format-version", "1", "--filter-platform", TARGET))
    # Path crates of this workspace have no source; git crates do and are listed.
    packages = [p for p in meta["packages"]
                if p["source"] and (p["name"], p["version"]) in wanted]
    return sorted(packages, key=lambda p: (p["name"], p["version"]))


def render():
    rows = []
    for p in linked_crates():
        source = p.get("repository") or f"https://crates.io/crates/{p['name']}"
        rows.append(f"| `{p['name']}` | {p['version']} | {spdx(p['name'], p['license'])} | {source} |")
    return HEADER + "\n".join(rows) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("THIRD-PARTY.md is out of date; run tools/third-party.py", file=sys.stderr)
            sys.exit(1)
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
